name: base_app
description: Base app
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.7.0

dependencies:
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  fpdart: ^1.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^15.0.0
  injectable: ^2.5.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  url_strategy: ^0.3.0

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  freezed: ^3.0.3

  go_router_builder: ^2.9.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/lottie/
